
import '@fortawesome/fontawesome-free/css/all.min.css';
import './globals.css'

import { Inter_Tight } from 'next/font/google'
import { AOSInit } from './aoshook/aoshook';
import ImportBs from './importBs';


const filterInitialState = {
    country: null,
    name: null,
    code: null,
    degree: null,
    speciality: null,
    program: null,
    language: null,
    period: null,
    city: null,
    feeMin: null,
    feeMax: null,
    currency: null,
    sortBy: "asc",
    freeText: null,
    pageNumber: 1,
    pageSize: 150
};

const inter = Inter_Tight({ subsets: ['latin'] })

export const metadata = {
  title: 'Find study',
  description: 'Generated by create next app',
  icons: {
    icon: ['/favicon.ico?v=4'],
    apple: ['/apple-touch-icon.png?v4'],
    shortcut: ['/apple-touch-icon.png']
  }
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <AOSInit/>
      <body className={inter.className}>  
      <ImportBs/>
        <div>{children}</div>
      </body>
    </html>
  )
}
